ALTER TABLE uploads ADD COLUMN added timestamp;
UPDATE uploads SET added = CURRENT_TIMESTAMP;
ALTER TABLE uploads ALTER COLUMN added SET NOT NULL;
ALTER TABLE uploads ALTER COLUMN added SET DEFAULT CURRENT_TIMESTAMP;